M48
; DRILL file {KiCad 9.0.6} date 2026-08-01T23:21:46+0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-01T23:21:46+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X135.11Y-105.1
X140.89Y-105.1
T2
X105.0Y-105.0
X105.0Y-171.0
X171.0Y-105.0
X171.0Y-171.0
M30
